version: '{build}'

clone_depth: 50

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - gradlew.bat --version

build_script:
  - run-tests.bat

cache:
  - C:\Users\appveyor\.gradle\caches -> .gradle-wrapper\gradle-wrapper.properties
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties